version: '3.7'

services:
  backend:
    image: hss-sae-tasks-backend:latest
    container_name: hss-sae-tasks-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: file:/data/dev.sqlite
    volumes:
      - lite_db_data:/data

  frontend:
    image: hss-sae-tasks-frontend:latest
    container_name: hss-sae-tasks-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      AUTH_URL: https://clearstack.net/api/auth
      DATABASE_URL: file:/data/dev.sqlite
      NODE_ENV: production
      AUTH_TRUST_HOST: true
      API_URL: https://backend.clearstack.net
      AUTH_SECRET: ...
      AUTH_RESEND_KEY: ...
    volumes:
      - lite_db_data:/data

volumes:
  lite_db_data:
